In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("GDP_per_capita.csv")

In [7]:
df.head()

,Country Name,Country Code,Indicator Name,Indicator Code,1960,1961,1962,1963,1964,1965,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,ABW,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,27441.550210,28440.041690,30082.158420,30645.890600,22759.807180,26749.329610,30975.998910,35718.753120,39498.594130,NaN
1,Africa Eastern and Southern,AFE,GDP per capita (current US$),NY.GDP.PCAP.CD,186.089204,186.909053,197.367547,225.400079,208.962717,226.836135,...,1334.470500,1528.104224,1552.073722,1507.085600,1351.591669,1562.416175,1679.327622,1571.449189,1615.396356,NaN
2,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,522.082216,525.469771,491.337221,496.602504,510.787063,356.496214,357.261153,413.757895,NaN,NaN
3,Africa Western and Central,AFW,GDP per capita (current US$),NY.GDP.PCAP.CD,121.936832,127.451040,133.823783,139.004980,148.545883,155.561897,...,1630.039439,1574.230564,1720.140092,2216.385055,2030.861659,2112.794076,2138.473153,1841.855064,1411.337029,NaN
4,Angola,AGO,GDP per capita (current US$),NY.GDP.PCAP.CD,NaN,NaN,NaN,NaN,NaN,NaN,...,2051.814621,2790.718869,2860.093648,2493.678844,1759.356199,2303.908127,3682.113151,2916.136633,2665.874448,NaN

In [5]:
df.shape

(269, 70)

In [8]:
df.drop(['Indicator Name', 'Indicator Code'], axis=1, inplace=True)

In [9]:
df.head()

,Country Name,Country Code,1960,1961,1962,1963,1964,1965,1966,1967,...,2016,2017,2018,2019,2020,2021,2022,2023,2024,2025
0,Aruba,ABW,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,27441.550210,28440.041690,30082.158420,30645.890600,22759.807180,26749.329610,30975.998910,35718.753120,39498.594130,NaN
1,Africa Eastern and Southern,AFE,186.089204,186.909053,197.367547,225.400079,208.962717,226.836135,240.911794,243.773593,...,1334.470500,1528.104224,1552.073722,1507.085600,1351.591669,1562.416175,1679.327622,1571.449189,1615.396356,NaN
2,Afghanistan,AFG,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,522.082216,525.469771,491.337221,496.602504,510.787063,356.496214,357.261153,413.757895,NaN,NaN
3,Africa Western and Central,AFW,121.936832,127.451040,133.823783,139.004980,148.545883,155.561897,162.107340,144.940804,...,1630.039439,1574.230564,1720.140092,2216.385055,2030.861659,2112.794076,2138.473153,1841.855064,1411.337029,NaN
4,Angola,AGO,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,2051.814621,2790.718869,2860.093648,2493.678844,1759.356199,2303.908127,3682.113151,2916.136633,2665.874448,NaN

In [10]:
country_codes = [
"AFG","ALB","DZA","AND","AGO","ATG","ARG","ARM","AUS","AUT","AZE","BHS","BHR","BGD",
"BRB","BLR","BEL","BLZ","BEN","BTN","BOL","BIH","BWA","BRA","BRN","BGR","BFA","BDI",
"CPV","KHM","CMR","CAN","CAF","TCD","CHL","CHN","COL","COM","COG","CRI","HRV","CUB",
"CYP","CZE","CIV","COD","DNK","DJI","DMA","DOM","ECU","EGY","SLV","GNQ","ERI","EST",
"SWZ","ETH","FJI","FIN","FRA","GAB","GMB","GEO","DEU","GHA","GRC","GRD","GTM","GIN",
"GNB","GUY","HTI","HND","HUN","ISL","IND","IDN","IRN","IRQ","IRL","ISR","ITA","JAM",
"JPN","JOR","KAZ","KEN","KIR","KWT","KGZ","LAO","LVA","LBN","LSO","LBR","LBY","LIE",
"LTU","LUX","MDG","MWI","MYS","MDV","MLI","MLT","MHL","MRT","MUS","MEX","FSM","MDA",
"MCO","MNG","MNE","MAR","MOZ","MMR","NAM","NRU","NPL","NLD","NZL","NIC","NER","NGA",
"PRK","MKD","NOR","OMN","PAK","PLW","PSE","PAN","PNG","PRY","PER","PHL","POL","PRT",
"QAT","ROU","RUS","RWA","KNA","LCA","VCT","WSM","SMR","STP","SAU","SEN","SRB","SYC",
"SLE","SGP","SVK","SVN","SLB","SOM","ZAF","KOR","SSD","ESP","LKA","SDN","SUR","SWE",
"CHE","SYR","TJK","TZA","THA","TLS","TGO","TON","TTO","TUN","TKM","TUV","TUR","UGA",
"UKR","ARE","GBR","USA","URY","UZB","VUT","VAT","VEN","VNM","YEM","ZMB","ZWE"
]

In [11]:
len(country_codes)

195

In [12]:
df_filtered = df[df['Country Code'].isin(country_codes)]

In [19]:
years = [str(year) for year in range(2000,2025)]
df_final = df_filtered[['Country Name','Country Code'] + years]

In [20]:
df_final = df_final.sort_values(by='Country Name').reset_index(drop=True)

In [21]:
df_final.head()

,Country Name,Country Code,2000,2001,2002,2003,2004,2005,2006,2007,...,2015,2016,2017,2018,2019,2020,2021,2022,2023,2024
0,Afghanistan,AFG,174.930991,138.706822,178.954088,198.871116,221.763654,254.184249,274.218554,376.223152,...,565.569730,522.082216,525.469771,491.337221,496.602504,510.787063,356.496214,357.261153,413.757895,NaN
1,Albania,ALB,1160.420471,1326.416524,1479.838846,1908.699007,2446.909499,2741.721365,3057.772570,3743.055299,...,4199.539129,4457.634122,5006.360130,5897.654526,6069.439031,6027.913507,7242.455131,7756.961887,9730.869219,11377.775740
2,Algeria,DZA,1772.928691,1896.300209,1937.464114,2283.772993,2816.993850,3233.133396,3660.661047,4167.451699,...,4685.059027,4424.985290,4554.667540,4577.210292,4468.453419,3743.541952,4160.559267,4960.303343,5370.477235,5752.990767
3,Andorra,AND,21810.250380,23511.296950,26528.130060,34063.575600,39021.110710,40829.811640,43467.196310,48336.254830,...,38654.952880,40129.838580,40672.971740,42819.757750,41257.816460,37361.107010,42425.706650,42414.047990,46812.426100,49303.649170
4,Angola,AGO,563.733796,533.586202,999.065856,1133.663320,1451.471179,2145.886211,2930.444286,3515.056790,...,3641.728939,2051.814621,2790.718869,2860.093648,2493.678844,1759.356199,2303.908127,3682.113151,2916.136633,2665.874448

In [22]:
df_final.shape

(194, 27)

In [23]:
for year in years:
    temp_df = df_final[['Country Name', 'Country Code', year]].copy()
    
    # Rename column to something clean
    temp_df = temp_df.rename(columns={year: 'GDP per capita(current US$)'})

    # ADD year column 
    temp_df['Year'] = int(year)

    # Reorder columns
    temp_df = temp_df[['Country Name', 'Country Code', 'Year', 'GDP per capita(current US$)']]
    
    # Save file
    temp_df.to_csv(f"{year}_gdp_per_capita.csv", index=False)

In [24]:
df_final.to_csv("Cleaned_GDP_Per_Capita_2000_2024.csv", index=False)

Find Missing Values

In [25]:
df_final['Missing Count'] = df_final[years].isnull().sum(axis=1)

# Get missing years list
df_final['Missing Years'] = df_final[years].isnull().apply(
    lambda row: [year for year in years if row[year]], axis=1
)

df_missing_only = df_final[df_final['Missing Count'] > 0]

final_missing = df_missing_only[['Country Name', 'Country Code', 'Missing Count', 'Missing Years']]

final_missing.to_csv("missing_data_predictor-02_report.csv", index=False)